### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by bkaradzic** [JesusIslam/tldr#1]
I tried to use this lib on non-english text and it crashes.

I noticed this:
https://github.com/JesusIslam/tldr/blob/master/tldr.go#L192

Could you change it to use golang's unicode library to determine is it alpha numeric instead?

http://golang.org/pkg/unicode/#IsDigit
http://golang.org/pkg/unicode/#IsLetter

Thanks!

**Comment by JesusIslam** [comment]
Yea, it's been bothering me for some time... but it is fixed now with the release of v0.1.2.
