### ISSUE TITLE
Strange check in summarize function

### ISSUE THREAD

**Issue by slavablind91** [JesusIslam/tldr#11]
In function 
```go
func (bag *Bag) Summarize(text string, num int) (string, error)
``` 
checking number of sentences for output
```go
if num > (len(bag.Ranks)-1) || num < 1 {
	num = 1
}
```

Why `len(Ranks)-1`?

May be need:
```go
if num > len(bag.Ranks) || num < 1 {
	num = 1
}
```
?

**Comment by slavablind91** [comment]
If i call `Summarize(text, 3)` and bag has 3 Ranks, i'va got only 1, because `3 > len(Ranks)-1 == true`

**Comment by slavablind91** [comment]
#12 for fix it

**Comment by slavablind91** [comment]
@JesusIslam And how about to return from `Summarize` not more than `num` sentences??

**Comment by JesusIslam** [comment]
@slavablind91 the current behavior is to only return the highest ranked sentence
