### ISSUE TITLE
Difference between createSentences and createOriginalSentences

### ISSUE THREAD

**Issue by neurosnap** [JesusIslam/tldr#3]
Hi, I have a sentence tokenizer that I want to use instead of the one used in this package, but I'm a little confused as to what I need to replace to get it working properly.

It looks like createOriginalSentences returns `[]string` whereas createSentences returns `[][]string`.

It'd be nice to have one function to replace the sentence tokenizer so anyone can swap it out.

**Comment by JesusIslam** [comment]
Hi @neurosnap , I am sorry it took so long for me to reply. I got busy lately.

`createOriginalSentences` returns `[]string` of chronologically ordered sentences.

For example: `[]string{"I am here", "Not anymore"}`

Meanwhile, `createSentences` returns `[][]string` of tokenized and deduplicated sentences to be worked by the summarizer.

I'll look into your request of modular tokenizer but I can't promise you the time. 

Thank you for your question.
