### ISSUE TITLE
multiple-value bag.Summarize() in single-value context

### ISSUE THREAD

**Issue by deepak-420** [JesusIslam/tldr#6]
I ran into this issue when I used your code provided in README.md
```
package main

import (
	"fmt"
	"io/ioutil"
	"github.com/JesusIslam/tldr"
)

func main() {
	intoSentences := 3
	textB, _ := ioutil.ReadFile("./sample.txt")
	text := string(textB)
	bag := tldr.New()
	result := bag.Summarize(text, intoSentences)
	fmt.Println(result)
}
```
But in your code Summarize function returns two values, i.e. result and error. 
For me modifying the line `result := bag.Summarize(text, intoSentences)` worked. Please check and modify README.md file.

**Comment by JesusIslam** [comment]
Thank you, it's been changed.

https://github.com/JesusIslam/tldr/commit/58d76639d9d955f1d50013d8e8ba75601935e942
